Add recommendations
UsenkoEvgeniy/java-filmorate pull request #14
Opened 2023-04-14 10:40 UTC by fernandocortez8547

2023-04-14 11:49 UTC, DevSMike commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return filmStorage.getAllFilms().stream().filter(f -> finalUniqueFilms.contains(f.getId())).collect(Collectors.toList());
мне кажется, что подобного рода выборку лучше делать через SQL запрос, т.к. так будет быстрее, но если пока не особо хочется с этим заморачиваться, можем подождать ревью проекта

2023-04-14 11:50 UTC, DevSMike approved these changes
все хорошо сделано, на комментарий в UserService можешь обратить внимание

2023-04-14 12:37 UTC, MadraySha2 approved these changes
Аналогично, по поводу коммента. Я бы лучше сделал через БД это, но можно оставить до ревью. Так мб лучше будет. 
Мой ревьюер на этот счет мне говорил, но мб наш общий не придерется

2023-04-14 13:16 UTC, UsenkoEvgeniy requested changes
Надо избавиться от сета в юзерах и не тягать всю базу фильмов в итоге.

2023-04-14 13:16 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  }
Может вместо добавления поля в user лучше просто вытаскивать id юзеров и фильмов которые они пролайкали отдельно, оно все равно нам нужно только для логики поиска id фильмов.

2023-04-14 13:16 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/UserDbStorage.java
> +                "WHERE l2.user_id <>:id";
SQL запрос сейчас вытаскивает любого юзера, который хотя бы один раз пролайкал любой фильм, а не тех, кто пролайкал те же самые.

2023-04-14 13:16 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return filmStorage.getAllFilms().stream().filter(f -> finalUniqueFilms.contains(f.getId())).collect(Collectors.toList());
Тягать всю базу по фильмам, чтобы достать несколько - выглядит неправильно.

2023-04-15 05:01 UTC, UsenkoEvgeniy requested changes
По прежнему не работает sql запрос. Всю логику отбора фильмов можно вместить в один запрос с 2-3 подзапросами.
Этот sql запрос должен выбирать из базы все лайки юзеров, для этого WHERE должно быть не внутри JOIN, а после него, сначала по левой фильтруешь айди нашего юзера, т.е. мы выберем пары юзер-фильм-юзер2 (где юзер2 - это все те, кто поставил лайк этому же фильму) и тут же фильтруешь юзер2, чтобы убрать лайки самого юзера. На выходе получаем колонку юзер2 - это все те, кто поставил лайки тем же фильмам, что и наш юзер. В этом же запросе мы можем сделать группировку юзер2 и сортировку по COUNT() DESC, в итоге мы получим столбец со всеми пользователями отсортированными по количеству совпадающих лайков, добавляем к этому LIMIT 1 и получаем id пользователя с максимальным количеством пересечений по лайкам.
Получается - это станет первым подзапросом.
Теперь отберем все фильмы, которые есть у этого пользователя в film_likes и из них вычтем те, которые уже есть у нашего юзера - получили список фильмов, который мы и должны вернуть.
Получился второй подзапрос.
И вот этот подзапрос мы вставляем в условие IN и у тебя вернется сразу коллекция фильмов.

2023-04-16 06:10 UTC, UsenkoEvgeniy requested changes

2023-04-16 06:10 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/UserDbStorage.java
>                  "FROM users u " +
l.film_id , похоже, осталось от предыдущих вариантов кода, надо убрать

2023-04-16 06:10 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/UserDbStorage.java
> +        String sql = "SELECT u.user_id, email, login, name, birthday, friend_id, status, l.film_id " +
и тут тоже

2023-04-16 06:10 UTC, UsenkoEvgeniy commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +public class UserServiceTest {
здесь убрать public

2023-04-16 06:10 UTC, UsenkoEvgeniy commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +    UserServiceTest(UserService userService, FilmService filmService) {
а конструктору, все же, лучше вернуть

2023-04-16 06:30 UTC, UsenkoEvgeniy approved these changes

2023-04-16 06:30 UTC, merged