feat: реализовать функциональность "Лента Событий"
UsenkoEvgeniy/java-filmorate pull request #15
Opened 2023-04-14 11:28 UTC by DevSMike

2023-04-14 15:35 UTC, UsenkoEvgeniy requested changes
Нужно поправить

2023-04-14 15:35 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/model/event/Event.java
> +    final long timestamp;
Почему не использовать просто Timestamp

2023-04-14 15:35 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/model/event/Event.java
> +    final String operation;
Зачем нам enum, если мы сохраняем стринги, нужно либо поставить тут Enum'ы, либо убрать классы Enum'ов

2023-04-14 15:35 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/EventDbStorage.java
> +        long eventId = jdbcTemplate.queryForObject("SELECT event_id FROM event ORDER BY event_id DESC LIMIT 1;", Long.class);
Зачем здесь доставать id Event? Если метод ничего не возвращает, то последние две строчки можно просто убрать. Если же id нужен, то лучше сразу использовать KeyHolder

2023-04-14 15:35 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/EventDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> makeEvent(rs), id).get(0);
Вместо списка здесь лучше сразу сделать queryForObject

2023-04-14 15:35 UTC, UsenkoEvgeniy commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/EventDbStorage.java
> +        return new ArrayList<>(jdbcTemplate.query(sql, (rs, rowNum) -> makeEvent(rs), id));
Зачем список заворачивать в еще один список, создание ArrayList можно убрать

2023-04-14 15:35 UTC, UsenkoEvgeniy commented on src/main/resources/schema.sql
> +event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
надо добавить отступы для значений

2023-04-15 22:44 UTC, tek822 requested changes
Точно стоит поменять в схеме sql для всех id INT на BIGINT.
Остальное на собственное усмотрение.

2023-04-15 22:44 UTC, tek822 commented on src/main/resources/schema.sql
> +    entity_id INTEGER,
Тип переменных *_id должен быть BIGINT

2023-04-15 22:44 UTC, tek822 commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/EventDbStorageTest.java
> +        user2Id = userService.getAllUsers().stream().filter(x -> x.getName().equals("name2")).findFirst().get().getId();
Можно ли упростить, чтобы не дергать всю базу для поиска id, которые и так возвращаются?
userId = userService.addUser(user).getId();
user2Id = userService.addUser(user2).getId();

2023-04-15 22:44 UTC, tek822 commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/EventDbStorageTest.java
> +        filmId = filmService.getAllFilms().stream().filter(x -> x.getName().equals("First Movie")).findFirst().get().getId();
Аналогично вычислению id пользователей.

2023-04-15 22:44 UTC, tek822 commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorageTest.java
> +        long user2Id = userStorage.getAllUsers().stream().filter(x -> x.getName().equals("name2")).findFirst().get().getId();
Аналогично предыдущим замечаниям.

2023-04-15 22:44 UTC, tek822 commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorageTest.java
> +        long film2Id = filmStorage.getAllFilms().stream().filter(x -> x.getName().equals("Second Movie")).findFirst().get().getId();
И здесь.

2023-04-16 07:58 UTC, UsenkoEvgeniy requested changes
Все отлично, только в schema.sql поправить регистр, в pom заменить и слить с актуальной develop, чтобы не было конфликтов.

2023-04-16 07:58 UTC, UsenkoEvgeniy commented on src/main/resources/schema.sql
> +    operation varchar(6)
VARCHAR нужно в верхнем регистре

2023-04-16 07:58 UTC, UsenkoEvgeniy commented on pom.xml
> +				</configuration>
Зачем useFile, тесты наши починит
        <configuration>
          <argLine>-Dfile.encoding=UTF-8</argLine>
        </configuration>

2023-04-16 11:47 UTC, UsenkoEvgeniy approved these changes

2023-04-16 12:54 UTC, tek822 approved these changes
Замечательно, давайте соберем все в одно целое.

2023-04-16 13:52 UTC, merged