Add search
UsenkoEvgeniy/java-filmorate pull request #18
Opened 2023-04-14 18:36 UTC by tek822

Добавлены локальные тесты к функциональности поиска фильмов.

2023-04-14 18:44 UTC, UsenkoEvgeniy requested changes
Все отлично, только пару мелочей поправить

2023-04-14 18:44 UTC, UsenkoEvgeniy commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorageSearchTest.java
> +public class FilmDbStorageSearchTest {
Надо убрать public

2023-04-14 18:44 UTC, UsenkoEvgeniy commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorageSearchTest.java
> +    private NamedParameterJdbcTemplate jdbcTemplate;
а это поле унести в initDb

2023-04-14 19:43 UTC, tek822 commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorageSearchTest.java
> +public class FilmDbStorageSearchTest {
Сделано

2023-04-14 19:43 UTC, tek822 commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorageSearchTest.java
> +    private NamedParameterJdbcTemplate jdbcTemplate;
И это сделано

2023-04-14 19:44 UTC, UsenkoEvgeniy approved these changes
Все отлично

2023-04-16 01:12 UTC, DevSMike approved these changes

2023-04-16 06:37 UTC, merged